USE [master]
GO

/****** Object:  Database [DBQUANLYBANHANG]    Script Date: 11/2/2023 3:07:34 PM ******/
CREATE DATABASE [DBQUANLYBANHANG]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBQUANLYBANHANG', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DBQUANLYBANHANG.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBQUANLYBANHANG_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DBQUANLYBANHANG_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBQUANLYBANHANG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBQUANLYBANHANG] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET  MULTI_USER 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBQUANLYBANHANG] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBQUANLYBANHANG] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DBQUANLYBANHANG] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DBQUANLYBANHANG] SET  READ_WRITE 
GO

